src/python/run bfs testes/bfs/1.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/1.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/2.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/2.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/3.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/3.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/4.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/4.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/5.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/5.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/6.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/6.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/7.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/7.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/8.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/8.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
src/python/run bfs testes/bfs/9.g: Fail
  ** STDOUT **
    parametros:
    bfs
    /home/jao/graphun/testes/bfs/9.g
    
  ** STDERR **
    Traceback (most recent call last):
      File "main.py", line 59, in <module>
        main()
      File "main.py", line 55, in main
        abreArquivo()
      File "main.py", line 7, in abreArquivo
        arquivo = open(sys.argv[1],"r")
    IOError: [Errno 2] No such file or directory: 'bfs'
  ** ERRORS **
    formatação: linha não tem 3 valores: parametros:
Total: 9  Errors: 9 (1s 408ms)
